
name: dev
root: ~/Development/densebrain/epictask-workspace/epictask

windows:
  - epictaskdev:
      layout: even-horizontal
      panes:
        - npm run tsc-watch
        - npm run compile-watch
