// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/redux-thunk/redux-thunk.d.ts
// Type definitions for redux-thunk v2.0.1
// Project: https://github.com/gaearon/redux-thunk
// Definitions by: Qubo <https://github.com/tkqubo>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped



declare module "redux-thunk" {
    import * as Redux from 'redux'
    namespace ReduxThunk {

        export interface Thunk extends Redux.Middleware {}
        export interface ThunkInterface {
            <T>(dispatch: Redux.Dispatch<any>, getState?: () => T): any;
        }
    }
    var thunk: ReduxThunk.Thunk;
    export default thunk;
}