// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/8c9d2af6b3aa98491ac8996a299bf4715715fd73/radium/radium.d.ts
declare module 'radium' {
    import React = require('react');

    interface ReactComponent<P, S> {
        new (p: P): React.Component<P, S>;
    }

    var Radium: {
        <T>(comp: T): T;
    };

    export = Radium;
}